---
- name: create base directories
  become: true
  file:
    path: "{{item.path}}"
    mode: 0755
    state: directory
  with_items:
    - {path: "/var/lib/kubelet"}
    - {path: "/opt/cni"}
    - {path: "/var/lib/kube_certs"}
    - {path: "/etc/calico"}

- name: copy ca pem
  become: true
  copy:
    mode: 0755
    src: /var/lib/kube_certs/ca.pem
    dest: /var/lib/kube_certs/ca.pem
  notify:
    - restart kubelet
    - restart kube-proxy

- name: copy cert
  become: true
  copy:
    mode: 0755
    src: /var/lib/kube_certs/kubernetes.pem
    dest: /var/lib/kube_certs/kubernetes.pem
  notify:
    - restart kubelet
    - restart kube-proxy

- name: copy cert key
  become: true
  copy:
    mode: 0755
    src: /var/lib/kube_certs/kubernetes-key.pem
    dest: /var/lib/kube_certs/kubernetes-key.pem
  notify:
    - restart kubelet
    - restart kube-proxy

- name: copy kubeconfig
  become: true
  template:
    mode: 0755
    src: /etc/ansible/roles/kubernetes/files/yaml_templatez/kubeconfig
    dest: /var/lib/kubelet/kubeconfig
  notify:
    - restart kubelet
    - restart kube-proxy

- name: download docker binary
  become: true
  unarchive:
    src: https://get.docker.com/builds/Linux/x86_64/docker-1.12.1.tgz
    dest: /tmp
    remote_src: True
    creates: /tmp/docker/docker

- name: copy docker binaries to bin
  become: true
  copy:
    mode: 0755
    src: /tmp/docker/{{ item }}
    dest: /usr/bin/{{ item }}
    remote_src: yes
  with_items:
    - docker
    - docker-containerd
    - docker-containerd-ctr
    - docker-containerd-shim
    - dockerd
    - docker-proxy
    - docker-runc

- name: download kubelet binary
  become: true
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/v1.5.2/bin/linux/amd64/kubelet
    dest: /usr/bin/kubelet
    mode: 0755

- name: download kube-proxy binary
  become: true
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/v1.5.2/bin/linux/amd64/kube-proxy
    dest: /usr/bin/kube-proxy
    mode: 0755

- name: download cni files
  become: true
  unarchive:
    src:  https://storage.googleapis.com/kubernetes-release/network-plugins/cni-07a8a28637e97b22eb8dfe710eeae1344f69d16e.tar.gz
    dest: /opt/cni
    remote_src: True
    creates: /opt/cni/bin/bridge

- name: docker_service_config
  become: true
  template:
    src: /etc/ansible/roles/kubernetes/files/systemd_templatez/docker.service
    dest: /etc/systemd/system/docker.service
    mode: 0755

- name: kubelet_service_config
  become: true
  template:
    src: /etc/ansible/roles/kubernetes/files/systemd_templatez/kubelet.service
    dest: /etc/systemd/system/kubelet.service
    mode: 0755
  notify:
    - restart kubelet

- name: kube-proxy_service_config
  become: true
  template:
    src: /etc/ansible/roles/kubernetes/files/systemd_templatez/kube-proxy.service
    dest: /etc/systemd/system/kube-proxy.service
    mode: 0755
  notify:
    - restart kube-proxy

- name: start k8s services
  become: true
  systemd:
    state: started
    enabled: yes
    name: "{{item}}"
  with_items:
    - docker
    - kubelet
    - kube-proxy

- name: download calicoctl binary
  become: true
  get_url:
    url: https://github.com/projectcalico/calicoctl/releases/download/v1.1.3/calicoctl
    dest: /usr/bin/calicoctl
    mode: 0755

- name: place calicoctl_cfg
  become: true
  template:
    mode: 0755
    src: /etc/ansible/roles/kubernetes/files/yaml_templatez/calicoctl_cfg
    dest: /etc/calico/calicoctl.cfg
